name = "agentbridge-webmcp-adapter-noapi"
account_id = "e484537a493a0d27262df4e998a5ca2d"
main = "worker/index.ts"
compatibility_date = "2026-09-02"

[vars]
TARGET_ORIGIN = "https://agentbridge-webmcp-noapi-adapter.agentbridge-noapi.workers.dev"
ORIGIN_UPSTREAM = "https://agentbridge-external-webmcp-powered-e.onrender.com"
