import { api, endpoint } from "../config/agentbridge";
import { type Permission, confirmationRequired } from "../security/permissions";
import { executeKnownApi } from "../executors/apiExecutor";

type Input = Record<string, unknown> & { confirmed?: boolean };
type Tool = { name: string; description: string; permission: Permission; inputSchema: Record<string, unknown>; run: (input: Input) => Promise<unknown> };
const obj = (properties: Record<string, unknown>, required: string[] = []) => ({ type: "object", properties, required, additionalProperties: false });
const string = { type: "string" }; const number = { type: "number" }; const integer = { type: "integer", minimum: 1 };
const confirm = async (name: string, permission: Permission, input: Input, execute: () => Promise<unknown>) => confirmationRequired(permission) && input.confirmed !== true ? { success: true, requiresConfirmation: true, action: name, message: `${name} requires explicit user confirmation.` } : execute();

export const tools: Tool[] = [
  { name: "search_products", description: "Search AgentBridge NoAPI products by keywords, category, brand, price, rating, and pagination.", permission: "READ", inputSchema: obj({ query: string, category: string, minPrice: number, maxPrice: number, brand: string, minRating: number, page: integer, limit: integer }), run: (i) => executeKnownApi({ method: "GET", path: api.searchProducts, query: { q: i.query, category: i.category, minPrice: i.minPrice, maxPrice: i.maxPrice, brand: i.brand, minRating: i.minRating, page: i.page, limit: i.limit } }) },
  { name: "get_product_details", description: "Get complete details, variants, pricing, and stock for one product.", permission: "READ", inputSchema: obj({ productId: string }, ["productId"]), run: (i) => executeKnownApi({ method: "GET", path: endpoint("/api/products", String(i.productId)) }) },
  { name: "filter_products", description: "Filter products by category, brand, price range, rating, and availability.", permission: "READ", inputSchema: obj({ category: string, brand: string, minPrice: number, maxPrice: number, minRating: number, stockStatus: string }), run: (i) => executeKnownApi({ method: "GET", path: api.filterProducts, query: i }) },
  { name: "sort_products", description: "Sort products using price_asc, price_desc, rating, newest, or popularity.", permission: "READ", inputSchema: obj({ sort: { type: "string", enum: ["price_asc", "price_desc", "rating", "newest", "popularity"] }, category: string }, ["sort"]), run: (i) => executeKnownApi({ method: "GET", path: api.searchProducts, query: { sort: i.sort, category: i.category } }) },
  { name: "get_product_recommendations", description: "Get popular or category-related product recommendations.", permission: "READ", inputSchema: obj({ category: string }), run: (i) => executeKnownApi({ method: "GET", path: api.recommendations, query: i }) },
  { name: "get_shipping_estimate", description: "Estimate shipping cost and delivery window for a country and postal code.", permission: "READ", inputSchema: obj({ postalCode: string, country: string }, ["postalCode", "country"]), run: (i) => executeKnownApi({ method: "GET", path: api.shipping, query: i }) },
  { name: "get_cart", description: "Get the signed-in user's current cart. Uses browser session credentials.", permission: "READ", inputSchema: obj({}), run: () => executeKnownApi({ method: "GET", path: api.cart }) },
  { name: "add_to_cart", description: "Add a product and optional variant to the signed-in user's cart.", permission: "WRITE", inputSchema: obj({ productId: string, variantId: string, quantity: integer }, ["productId", "quantity"]), run: (i) => executeKnownApi({ method: "POST", path: api.cartItems, body: i }) },
  { name: "update_cart", description: "Set the quantity for one existing cart item.", permission: "WRITE", inputSchema: obj({ itemId: string, quantity: integer }, ["itemId", "quantity"]), run: (i) => executeKnownApi({ method: "PATCH", path: endpoint(api.cartItems, String(i.itemId)), body: { quantity: i.quantity } }) },
  { name: "remove_from_cart", description: "Remove one item from the cart. Requires confirmation.", permission: "DESTRUCTIVE", inputSchema: obj({ itemId: string, confirmed: { type: "boolean" } }, ["itemId"]), run: (i) => confirm("remove_from_cart", "DESTRUCTIVE", i, () => executeKnownApi({ method: "DELETE", path: endpoint(api.cartItems, String(i.itemId)) })) },
  { name: "clear_cart", description: "Remove every item from the cart. Requires confirmation.", permission: "DESTRUCTIVE", inputSchema: obj({ confirmed: { type: "boolean" } }), run: (i) => confirm("clear_cart", "DESTRUCTIVE", i, () => executeKnownApi({ method: "DELETE", path: api.cart })) },
  { name: "get_wishlist", description: "Get the signed-in user's wishlist.", permission: "READ", inputSchema: obj({}), run: () => executeKnownApi({ method: "GET", path: api.wishlist }) },
  { name: "add_to_wishlist", description: "Save a product to the signed-in user's wishlist.", permission: "WRITE", inputSchema: obj({ productId: string }, ["productId"]), run: (i) => executeKnownApi({ method: "POST", path: api.wishlistItems, body: { productId: i.productId } }) },
  { name: "remove_from_wishlist", description: "Remove a product from the signed-in user's wishlist.", permission: "WRITE", inputSchema: obj({ productId: string }, ["productId"]), run: (i) => executeKnownApi({ method: "DELETE", path: endpoint(api.wishlistItems, String(i.productId)) }) },
  { name: "get_orders", description: "Get the signed-in user's order history.", permission: "READ", inputSchema: obj({}), run: () => executeKnownApi({ method: "GET", path: api.orders }) },
  { name: "get_order_details", description: "Get an order owned by the signed-in user.", permission: "READ", inputSchema: obj({ orderId: string }, ["orderId"]), run: (i) => executeKnownApi({ method: "GET", path: endpoint(api.orders, String(i.orderId)) }) },
  { name: "cancel_order", description: "Cancel an eligible order. Requires confirmation.", permission: "DESTRUCTIVE", inputSchema: obj({ orderId: string, confirmed: { type: "boolean" } }, ["orderId"]), run: (i) => confirm("cancel_order", "DESTRUCTIVE", i, () => executeKnownApi({ method: "POST", path: `${endpoint(api.orders, String(i.orderId))}/cancel` })) },
  { name: "apply_coupon", description: "Apply a coupon code to the current cart.", permission: "WRITE", inputSchema: obj({ code: string }, ["code"]), run: (i) => executeKnownApi({ method: "POST", path: api.cartCoupon, body: { code: i.code } }) },
  { name: "checkout", description: "Place a mock order using a country and postal code. Requires explicit confirmation.", permission: "TRANSACTIONAL", inputSchema: obj({ country: string, postalCode: string, paymentMethod: { type: "string", enum: ["mock"] }, confirmed: { type: "boolean" } }, ["country", "postalCode"]), run: (i) => confirm("checkout", "TRANSACTIONAL", i, () => executeKnownApi({ method: "POST", path: api.checkout, body: { country: i.country, postalCode: i.postalCode, paymentMethod: "mock" } })) },
];
